---
title: "Patel et al. 2024 revision, Nanopore analysis"
output: html_notebook
---

Read packages and methylation utilities:  
```{r utils, message = F, warning = F}
source("R/methylation_R_utils.R")
source("R/style.R")

library(tidyverse)
library(bsseq)
library(GenomicRanges)
library(BiocParallel)

p <- MulticoreParam(workers = 40, progressbar = T)
```


Read the BSmoothed data in for GP5d WT and DNMTi+HDACi:  
```{r import data, message = F, warning = F}

# gp5d_meth <- read.bismark("/data/kzkarttu/nanopore/GP5D/methylation/methylation_calls.GP5D.raw.cpg.mfreq.txt.gz")
# gp5d_inh_meth <- read.modkit("/data/kzkarttu/projects/Patel_2024_revision/data/Nanopore/GP5d_DNMTi_HDACi/methylation/GP5d_DNMTi_HDACi_bedMethyl_no_GCG.bed.gz")
# gp5d_meth_comb <- bsseq::combine(gp5d_meth, gp5d_inh_meth)

# gp5d_meth_comb_smooth <- BSmooth(gp5d_meth_comb, BPPARAM = p)
# saveRDS(gp5d_meth_comb_smooth, "data/bsmooth/GP5d_WT_inh_CpG_bsmoothed.rds")

gp5d_meth_comb_smooth <- readRDS("data/bsmooth/GP5d_WT_inh_CpG_bsmoothed.rds")
ltr12c_loci <- read_tsv("data/LTR12C/LTR12C_DNMT_HDAC_Up_bothstrand_GP5d.bed", col_names = c("seqnames", "start", "end", "name", "width", "strand"))
```

Tabulate methylation per each LTR12C locus in GP5d WT and GP5d DNMTi+HDACi

```{r get_methylation}
ltr12c_meth <- getMeth(gp5d_meth_comb_smooth, regions = GRanges(ltr12c_loci), type = "smooth")

ltr12c_meth_all <- bind_rows(lapply(1:nrow(ltr12c_loci), function(i) {
  
  bind_cols(ltr12c_loci[i,], as_tibble(ltr12c_meth[[i]]) %>% 
              rename(GP5d_WT = V1, GP5d_inh = V2))
}))

```

Plot aggregated methylation difference in both GP5d cell lines, in a \pm 600bp window around the center of all the 500 LTR12C peaks.

```{r plot_methylation_data}
plot_meth <- bind_rows(makeMethPlot(gp5d_meth_comb_smooth[,1], GRanges(ltr12c_loci)),
                       makeMethPlot(gp5d_meth_comb_smooth[,2], GRanges(ltr12c_loci)),
                       .id = "line") %>% 
  mutate(line = if_else(line == 1, "GP5d WT", "GP5d DNMTi + HDACi"),
         dist = plot_meth$dist - median(plot_meth$dist))
```

```{r plot_methylation}
ggplot(plot_meth, aes(x = dist, y = freq, color = line)) +
  geom_line(size = 1) +
  xlab("Distance (bp)") +
  ylab("Methylation frequency") +
  scale_x_continuous(limits = c(-600, 600)) +
  scale_y_continuous(limits = c(0.3, 1))
```









